# Generated by Django 4.2 on 2024-10-02 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('performances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('seatscale', models.IntegerField()),
                ('relateurl', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('telno', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('kopis_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('facility_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100, null=True)),
                ('start_date', models.CharField(max_length=20)),
                ('end_date', models.CharField(max_length=20)),
                ('cast', models.CharField(max_length=10)),
                ('crew', models.CharField(max_length=10)),
                ('runtime', models.IntegerField(null=True)),
                ('age', models.IntegerField()),
                ('entprsmnP', models.CharField(max_length=100)),
                ('entrprsnmA', models.CharField(max_length=100)),
                ('pricing', models.IntegerField()),
                ('synopsis', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=10)),
                ('visit', models.BooleanField(default=False)),
                ('daehakro', models.BooleanField(default=False)),
                ('festival', models.BooleanField(default=False)),
                ('musicallicense', models.BooleanField(default=False)),
                ('musicalcreate', models.BooleanField(default=False)),
                ('dtguidance', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='like',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('title', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performances.article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to='performances.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='performancelike',
            constraint=models.UniqueConstraint(fields=('user', 'article'), name='unique_like'),
        ),
    ]
