# Generated by Django 4.2 on 2024-10-01 02:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('performances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_performance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
