# Generated by Django 4.2 on 2024-10-08 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='performancelike',
            name='unique_like',
        ),
    ]
