# Generated by Django 4.2 on 2024-10-06 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('performances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('kopis_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('seatscale', models.IntegerField()),
                ('relateurl', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('telno', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Performlist',
            fields=[
                ('kopis_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('facility_name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100, null=True)),
                ('start_date', models.CharField(max_length=20)),
                ('end_date', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='like',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('title', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performances.article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to='performances.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('kopis_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, null=True)),
                ('state', models.CharField(max_length=20)),
                ('start_date', models.CharField(max_length=20)),
                ('end_date', models.CharField(max_length=20)),
                ('facility_name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=10)),
                ('area', models.CharField(max_length=10)),
                ('synopsis', models.TextField(blank=True, null=True)),
                ('cast', models.CharField(max_length=100)),
                ('crew', models.CharField(max_length=100)),
                ('runtime', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=10)),
                ('production', models.CharField(max_length=20)),
                ('agency', models.CharField(max_length=20)),
                ('pricing', models.CharField(max_length=100)),
                ('visit', models.CharField(max_length=2)),
                ('daehakro', models.CharField(max_length=2)),
                ('festival', models.CharField(max_length=2)),
                ('musicallicense', models.CharField(max_length=2)),
                ('musicalcreate', models.CharField(max_length=2)),
                ('dtguidance', models.CharField(max_length=100)),
                ('poster', models.TextField()),
                ('styurl', models.TextField()),
                ('facility_kopis_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='performance_facility', to='performances.facility')),
            ],
        ),
        migrations.AddConstraint(
            model_name='performancelike',
            constraint=models.UniqueConstraint(fields=('user', 'article'), name='unique_like'),
        ),
    ]
