# Generated by Django 4.2 on 2024-10-03 06:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('seatscale', models.IntegerField()),
                ('relateurl', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('telno', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='performancereview',
            name='like',
        ),
        migrations.AddField(
            model_name='performancereview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('cast', models.CharField(max_length=10)),
                ('crew', models.CharField(max_length=10)),
                ('runtime', models.IntegerField(null=True)),
                ('age', models.IntegerField()),
                ('entprsmnP', models.CharField(max_length=100)),
                ('entrprsnmA', models.CharField(max_length=100)),
                ('pricing', models.IntegerField()),
                ('poster', models.ImageField(upload_to='')),
                ('synopsis', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=10)),
                ('visit', models.BooleanField(default=False)),
                ('daehakro', models.BooleanField(default=False)),
                ('festival', models.BooleanField(default=False)),
                ('musicallicense', models.BooleanField(default=False)),
                ('musicalcreate', models.BooleanField(default=False)),
                ('dtguidance', models.CharField(max_length=100)),
                ('facility_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performances.facility')),
            ],
        ),
    ]
