# Generated by Django 4.2 on 2024-10-02 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0002_article_like_review_performancelike_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='article_id',
            new_name='article',
        ),
    ]
