# Generated by Django 4.2 on 2024-10-11 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0002_performancelike_unique_like'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='performancelike',
            name='unique_like',
        ),
    ]
