# Generated by Django 4.2 on 2024-10-01 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0002_performancelike'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerformanceLike',
        ),
    ]
