# Generated by Django 4.2 on 2024-10-02 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('performances', '0003_rename_article_id_review_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('seatscale', models.IntegerField()),
                ('relateurl', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('telno', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('cast', models.CharField(max_length=10)),
                ('crew', models.CharField(max_length=10)),
                ('runtime', models.IntegerField(null=True)),
                ('age', models.IntegerField()),
                ('entprsmnP', models.CharField(max_length=100)),
                ('entrprsnmA', models.CharField(max_length=100)),
                ('pricing', models.IntegerField()),
                ('poster', models.ImageField(upload_to='')),
                ('synopsis', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=10)),
                ('visit', models.BooleanField(default=False)),
                ('daehakro', models.BooleanField(default=False)),
                ('festival', models.BooleanField(default=False)),
                ('musicallicense', models.BooleanField(default=False)),
                ('musicalcreate', models.BooleanField(default=False)),
                ('dtguidance', models.CharField(max_length=100)),
                ('facility_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='performances.facility')),
            ],
        ),
    ]
