# Generated by Django 4.2 on 2024-10-01 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('performances', '0005_alter_performancelike_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancelike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
