# Generated by Django 4.2 on 2024-10-01 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0006_alter_performancelike_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
