# Generated by Django 4.2 on 2024-10-01 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('performances', '0007_article_like_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancelike',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performances.article'),
        ),
        migrations.AlterField(
            model_name='performancelike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
