# Generated by Django 4.2 on 2024-10-01 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performances', '0009_alter_performancelike_article_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='like_count',
            new_name='like',
        ),
    ]
