# Generated by Django 4.2 on 2024-09-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('남', '남성'), ('여', '여성')], max_length=1, null=True),
        ),
    ]
